# Generated by Django 2.1.4 on 2019-03-30 15:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя статуса')),
                ('status_text', models.CharField(max_length=30, verbose_name='Текст статуса')),
            ],
            options={
                'verbose_name': 'Тревожный статус',
                'verbose_name_plural': 'Тревожный статус',
            },
        ),
        migrations.CreateModel(
            name='Area_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_coords_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Широта')),
                ('point_coords_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Долгота')),
                ('array_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Координаты зоны ответственности датчика',
                'verbose_name_plural': 'Координаты зоны ответственности датчика',
            },
        ),
        migrations.CreateModel(
            name='Area_Points_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Список координат',
                'verbose_name_plural': 'Список координат',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя области')),
                ('coords_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Area_Points_List', verbose_name='Список координат')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Область',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('temp', models.IntegerField(blank=True, verbose_name='Температура')),
                ('wind_direction', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Направление ветра')),
                ('wind_speed', models.IntegerField(blank=True, verbose_name='Скорость ветра')),
                ('humidity', models.IntegerField(blank=True, verbose_name='Влажность')),
                ('sensor_coords_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Широта')),
                ('sensor_coords_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='Долгота')),
                ('coords_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Area_Points_List', verbose_name='Список координат')),
            ],
            options={
                'verbose_name': 'Датчики',
                'verbose_name_plural': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Data_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 30, 18, 6, 24, 700357))),
                ('temp', models.IntegerField(blank=True, verbose_name='Температура')),
                ('wind_direction', models.IntegerField(blank=True, verbose_name='Направление ветра')),
                ('wind_speed', models.IntegerField(blank=True, verbose_name='Скорость ветра')),
                ('humidity', models.IntegerField(blank=True, verbose_name='Влажность')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sensor')),
            ],
            options={
                'verbose_name': 'Список показателей датчиков',
                'verbose_name_plural': 'Список показателей датчиков',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Area_Points_List', verbose_name='Список координат')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Region', verbose_name='Список координат')),
            ],
            options={
                'verbose_name': 'Координаты зоны ответственности группы датчиков',
                'verbose_name_plural': 'Координаты зоны ответственности группы датчиков',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sensor_Group', verbose_name='Группа сенсеров'),
        ),
        migrations.AddField(
            model_name='area_point',
            name='points_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area_Points_List'),
        ),
    ]
