# Generated by Django 2.1.4 on 2019-03-30 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('temp', models.IntegerField(blank=True, verbose_name='Температура')),
                ('wind_direction', models.IntegerField(blank=True, verbose_name='Направление ветра')),
                ('wind_speed', models.IntegerField(blank=True, verbose_name='Скорость ветра')),
                ('humidity', models.IntegerField(blank=True, verbose_name='Влажность')),
                ('sensor_coords_lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('sensor_coords_lng', models.FloatField(blank=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Датчики',
                'verbose_name_plural': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Area_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_coords_lat', models.FloatField(blank=True, verbose_name='Широта')),
                ('point_coords_lng', models.FloatField(blank=True, verbose_name='Долгота')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sensor')),
            ],
            options={
                'verbose_name': 'Координаты зоны ответственности',
                'verbose_name_plural': 'Координаты зоны ответственности',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Data_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 30, 15, 31, 59, 411638))),
                ('temp', models.IntegerField(blank=True, verbose_name='Температура')),
                ('wind_direction', models.IntegerField(blank=True, verbose_name='Направление ветра')),
                ('wind_speed', models.IntegerField(blank=True, verbose_name='Скорость ветра')),
                ('humidity', models.IntegerField(blank=True, verbose_name='Влажность')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Sensor')),
            ],
            options={
                'verbose_name': 'Список показателей датчиков',
                'verbose_name_plural': 'Список показателей датчиков',
            },
        ),
    ]
